singleuser:
  image:
    registry: myregistry.localhost:49810
    repository: jupyter-base-notebook
    tag: 1.29
  command: /opt/versatel/start.sh

postgresql:
  enabled: true
  auth:
    username: bn_jupyterhub
    password: "rwpKmDjFtZ"
    postgresPassword: rwpKmDjFtZ
